= Starter: My first web app
:toc: right

A step-by-step tutorial for building your first web application with Enonic XP

WARNING: This documentation is currently under construction, do not use!

== Introduction

This guide will take you through the basic steps of creating a web app, using the basic building blocks of Enonic XP.

During this exercise you will:

* learn about http controllers
* serve assets
* create links
* use libraries
* try out the https://market.enonic.com/vendors/enonic/router-lib[router library]
* and more...

== Create project

To set up the development environment and initialize the project, follow the instructions in the https://developer.enonic.com/start[Getting started guide].

NOTE: *In step 2:* Choose "*My First Web app*" starter, and create a *new sandbox* for the project

====
After deploying, you should find an entry similar to this in the sandbox log:

  2019-04-09 13:40:40,765 INFO ... Application [<my.project.name>] installed successfully
====

== Project structure

The project folder created should now contain a project structure, looking something like this:

[source,files]
----
build.gradle <--1-->
settings.gradle
build/ <--2-->
src/
  main/
    java/ <!--3-->
    resources/ <!--4-->
      assets/
      webapp/ <!--5-->
      services/
----

<1> *.gradle files are used by the app build system
<2> Contains output files produced by the build
<3> Optional folder for Java code (used to import sample site in this starter)
<4> Main location for XP specific project code
<5> Folder containing the webapp controller


== Webapp controller

TODO


== Serving assets




== Using Views

TODO

Our first controller produced HTML directly.
According to the MVC (Model View Controller) pattern,
we should separate the View (template) from the controller.
In this step, we'll upgrade our page component to use the https://market.enonic.com/vendors/enonic/thymeleaf-lib[Thymeleaf templating engine]:

. To make sure Thymeleaf is added to our project, we must update the `gradle.build` file.
Uncomment the following line from the "dependencies" section:
+
      include "com.enonic.lib:lib-thymeleaf:2.0.0-RC1"
+
. Update the `webapp.js` controller with the code below:
+
. Redeploy the app:
+
  enonic project deploy
+

Refresh the site preview, and you should now see: "*Hello world - of views*" instead.


== Config management

TODO

Our app is using the Google Maps API.
Heavy usage of Googles services requires a valid API key.

Hardcoding an API key into your app is far from ideal.
Luckily, XP provides a simple way to inject configuration, like the API key, without having to change your app.

. Start by https://developers.google.com/maps/documentation/javascript/get-api-key[getting yourself a Google API key]
. Create a file called <name.of.your.app>.cfg i.e. "my.first.site.cfg" with the following content:
+
  maps.apiKey = <your google api key>
+
. Copy this file into your sandbox' config folder. The sandbox is located in your users home folder at .enonic/sandboxes/<name-of-sandbox>/home/config/
. After placing the file in the sandbox, you should now see a line from the sandbox log showing something like this:
+
  2019-05-05 20:07:39,462 INFO  c.e.x.s.i.config.ConfigInstallerImpl - Loaded config for [<name.of.your.app>]
+

To verify that the configuration is in use,
check the source code for a country page to see the following:
+
  <script src="http://maps.googleapis.com/maps/api/js?key=yourGoogleKey>"></script></head>
+


== Nice to know

=== Setting up vhosts

If you want to go live on a production server, you will need to configure a vhost.
Vhosts map the internal XP URI to a public facing URL i.e. mydomain.com -> /site/default/master/hello-world.

Read more about https://developer.enonic.com/docs/xp/stable/deployment/config#vhost[vhost configuration] in the XP docs.

=== Adding more apps

A site can be created from a single app, but you may also add more.
SEO Meta Fields, Disqus comments and Google Analytics are just a few of the many apps that can instantly add new features to your site.

To add an app, install an app from the "Applications" tool in the main menu.
Once installed, edit your site and add the application in the apps field.

=== Logging

While developing an app, it can be helpful to see the structure of objects returned by library functions.
A way to do this is by creating up a small utility script.

.src/main/resources/lib/utilities.js
[source,js]
----
exports.log = function (data) {
  log.info('Utilities log %s', JSON.stringify(data, null, 4));
};
----

Next, call the log function in any controller like the example below and then check the log after refreshing the page.

    var util = require('utilities');

    var content = portal.getContent();
    util.log(content);

This function and many more are included in the https://market.enonic.com/vendors/enonic/util-lib[Util Library]
